project:
  type: website
  output-dir: docs

website:
  title: "WHY4SOCIAL"
  site-url: "https://why4social.github.io"
  navbar:
    left:
      - text: "POSTS"
        href: index.html
      - text: "ABOUT"
        href: about.html
    right:
      - icon: github
        href: https://github.com/why4social

format:
  html:
    theme:
      dark: darkly
    css: styles.css
    toc: false
    grid:
      body-width: 900px