project:
  type: website
  output-dir: docs

website:
  title: "WHY4SOCIAL"
  site-url: "https://why4social.github.io"
  navbar:
    left:
      - text: "ABOUT"
        href: about.html
      - text: "RESEARCH"
        href: research.html
      - text: "GITHUB"
        href: https://github.com/why4social
    background: "#0e0e0e"
    foreground: "#d0d0d0"
  page-footer:
    center: "COPYRIGHT © 2025 WHY4SOCIAL. ALL RIGHTS RESERVED."
    background: "#0e0e0e"

format:
  html:
    theme:
      dark: darkly
    css: styles.css
    toc: false
    grid:
      body-width: 1100px
      margin-width: 0px